'use client';

import { FormEvent, useState } from 'react';
import { Check, Plus, X } from 'lucide-react';
import { apiFetch } from '../lib/api';

export function CategoryQuickCreate() {
  const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [error, setError] = useState(''); const [saved, setSaved] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); try { await apiFetch('/categories', { method: 'POST', body: JSON.stringify({ name }) }); setName(''); setSaved(true); window.setTimeout(() => { setSaved(false); setOpen(false); }, 900); } catch (cause) { setError((cause as Error).message); } }
  return <div className="relative">{open ? <form onSubmit={submit} className="absolute bottom-[calc(100%+0.5rem)] left-0 z-30 w-[min(18rem,calc(100vw-2rem))] rounded-2xl border border-[#e0e8df] bg-white p-4 shadow-xl"><div className="flex items-center justify-between"><strong className="text-sm text-[#355448]">Nueva categoría</strong><button type="button" onClick={() => setOpen(false)} aria-label="Cerrar nueva categoría" className="grid size-10 place-items-center rounded-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#6c9b77]"><X size={16} /></button></div><input autoFocus required minLength={2} value={name} onChange={(event) => setName(event.target.value)} placeholder="Ej. Congelados" className="mt-3 h-11 w-full rounded-xl border border-[#d5dfd7] px-3 text-sm outline-none focus:border-[#6c9b77]" />{error ? <p role="alert" className="mt-2 text-xs text-[#9b4f3e]">{error}</p> : null}<button className="mt-3 inline-flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-[#173d34] text-xs font-semibold text-white">{saved ? <Check size={15} /> : <Plus size={15} />} {saved ? 'Creada' : 'Guardar categoría'}</button></form> : null}<button onClick={() => setOpen(true)} className="inline-flex min-h-11 w-full items-center justify-center gap-1.5 rounded-xl border border-[#d5dfd7] bg-white px-2 text-[11px] font-semibold text-[#355448] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#6c9b77] sm:w-auto sm:gap-2 sm:rounded-full sm:px-4 sm:text-xs"><Plus size={16} /> Nueva categoría</button></div>;
}
