'use client';

import { useEffect, useState } from 'react';
import { ArrowRight, ListChecks, X } from 'lucide-react';
import { apiFetch } from '../lib/api';

type List = { id: string; title: string; status: string };
type Contact = { id: string; name: string; role: string };

export function ListAssignmentQuick() {
  const [open, setOpen] = useState(false); const [lists, setLists] = useState<List[]>([]); const [contacts, setContacts] = useState<Contact[]>([]); const [listId, setListId] = useState(''); const [contactId, setContactId] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (!open) return; Promise.all([apiFetch<List[]>('/lists'), apiFetch<Contact[]>('/users/contacts')]).then(([nextLists, nextContacts]) => { setLists(nextLists.filter((list) => list.status === 'ACTIVE')); setContacts(nextContacts); }).catch((cause: Error) => setError(cause.message)); }, [open]);
  async function assign() { setError(''); setMessage(''); try { await apiFetch(`/lists/${listId}/assign`, { method: 'PATCH', body: JSON.stringify({ assignedToId: contactId }) }); setMessage('Lista asignada correctamente.'); } catch (cause) { setError((cause as Error).message); } }
  return <><button onClick={() => setOpen(true)} className="fixed bottom-5 right-36 z-20 inline-flex items-center gap-2 rounded-full border border-[#d5dfd7] bg-white px-4 py-3 text-xs font-semibold text-[#355448] shadow-lg shadow-[#173d34]/10"><ListChecks size={16} /> Asignar lista</button>{open ? <div className="fixed inset-0 z-40 flex items-end justify-center bg-[#173d34]/25 p-0 backdrop-blur-sm sm:items-center sm:p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><section role="dialog" aria-modal="true" aria-labelledby="assign-title" className="max-h-[90vh] w-full max-w-md overflow-y-auto rounded-t-2xl bg-white p-5 shadow-2xl sm:rounded-2xl"><div className="flex items-center justify-between"><h2 id="assign-title" className="text-xl font-semibold text-[#355448]">Asignar lista a amigo</h2><button onClick={() => setOpen(false)} aria-label="Cerrar asignación"><X size={18} /></button></div><label className="mt-5 block text-sm font-semibold text-[#355448]">Lista<select value={listId} onChange={(event) => setListId(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-[#d5dfd7] bg-white px-3 text-sm"><option value="">Selecciona una lista</option>{lists.map((list) => <option key={list.id} value={list.id}>{list.title}</option>)}</select></label><label className="mt-4 block text-sm font-semibold text-[#355448]">Amigo<select value={contactId} onChange={(event) => setContactId(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-[#d5dfd7] bg-white px-3 text-sm"><option value="">Selecciona un contacto</option>{contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.name} · {contact.role}</option>)}</select></label>{message ? <p role="status" className="mt-3 text-sm text-[#52712e]">{message}</p> : null}{error ? <p role="alert" className="mt-3 text-sm text-[#9b4f3e]">{error}</p> : null}<button onClick={assign} disabled={!listId || !contactId} className="mt-5 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#173d34] text-sm font-semibold text-white disabled:opacity-40">Asignar <ArrowRight size={16} /></button></section></div> : null}</>;
}
